version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          name: "Make folder"
          command: mkdir test-results
      - run:
          name: "Run unit tests"
          command: python -m unittest discover -s .
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  build-workflow:
    jobs:
      - test