version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: python -m unittest discover -s .

workflows:
  build-workflow:
    jobs:
      - test